name: unittests for calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths: [ 'calc/calc.py' ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run tests and send notification about the build run
      shell: bash
      env:
        RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        SECRET_FLAG: ${{ secrets.SECRETFLAG }}
      run: |
        /usr/bin/python3 tests.py
        /usr/bin/curl -d "$RUN_URL" -X POST --header "Authorization: Bearer $SECRET_FLAG" https://notifications-alpha.wallsec.de/
